services:
  s6-market-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: s6-market-back
    hostname: backend.market.pdn
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
      #- ${API_PORT}:4000
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_COL: ${MONGODB_COL}
      API_PORT: ${API_PORT}
      API_PREFIX: ${API_PREFIX}
      